/**
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
  WARNING: DO NOT MODIFY OR DELETE
  This file is auto-generated by Quasar CLI
  It's recommended to NOT .gitignore it
  You don't have to use TypeScript in your project, don't worry
*/
import 'quasar/dist/types/feature-flag.d.ts';

declare module 'quasar/dist/types/feature-flag.d.ts' {
  interface QuasarFeatureFlags {
    store: true;
  }
}
